### ISSUE TITLE
Tool optimizes KL and returns relative Frobenius Norm

### ISSUE THREAD

**Issue by aerval** [bioinfo-cnb/bionmf-gpu#2]
We found that this tool converges to higher end distances than other NMF implementations that decompose with the Frobenius Norm as cost function. In the publication you write that you use the update rules proposed by _Lee & Seung 2001_ for minimizing Kullbach-Leibler Divergence. The current tool returns the relative Frobenius error:  ||X-WH|| / ||X|| which is quite irritating.

**Comment by edgardomejia** [comment]
I think there is a misunderstanding.

Indeed, the software *shows* the relative Frobenius error ||**X**-**WH**|| / ||**X**||, but it is just an *information message* (i.e., the value is computed once, *after* the algorithm has converged). As **clearly stated** in the paper, the test of convergence is based on the stability of *sample classifications* (matrix **H**) and thus, it ignores matrix **W**. This method is further explained in section "[*Test of Convergence*](../blob/master/doc/user_guide.txt.md#convergence)" of the [User Guide](../blob/master/doc/user_guide.txt.md)—did you read it?

Maybe, at some point in the future, I *might* try to add the capability of choosing which convergence test to use—the current one, or the Frobenius distance. However, this software was developed as part of my PhD I received a year ago, and I am not working anymore at that university nor I have access to a multi-GPU platform.

**Comment by aerval** [comment]
Why is this invalid? You implemented a NMF solver that descends to the lowest Kullbach-Leibler Divergence, so why does it return the relative Frobenius error but not KL? I know that convergence is determined in a different way but that does not interfere with the fact that, in the end, we evaluate a NMF run (among other criteria) by the cost function for which this tool returns the wrong one.

I understand that you may not have time to fix this, still it is important for users of this tool to know that the returned distance is of minor relevance. The problem for me is that quite a number of high impact papers state that they use NMF and minimize the Frobenius norm but then use some implementation based on _Brunet et al. 2004_ that minimizes KL.

**Comment by edgardomejia** [comment]
I implemented the Frobenius norm because it was planned to use it as an *alternative* convergence test, but it was not used since it requires further optimization to avoid hitting too much the global algorithm performance— hence, I just let it as the informational message `Distance between V and WH`. Nevertheless, I **never** mentioned it in the [paper](https://dx.doi.org/10.1186/s12859-015-0485-4) nor in the [installation](../blob/master/doc/installation_guide.txt.md)/[user](../blob/master/doc/user_guide.txt.md) guides—you have to look in the **source code** to know how such *"distance"* is calculated. In that case, you should have seen it is computed once, after the main loop (see [here](../blob/master/src/NMF_GPU.c#L861), and [here](../blob/master/src/NMF_mGPU.c#L2328)).

I understand your concern about papers stating they minimize Frobenius norm and then using another cost function, but that is not the case for this [one](https://dx.doi.org/10.1186/s12859-015-0485-4).
